LunarClient/Apollo

- common/src/main/java/com/lunarclient/apollo/option/OptionsImpl.java
This addresses the issue with reloading and any other option changes, where an option value remains unchanged but sends an update anyway. Fixes https://github.com/LunarClient/Apollo/issues/96
> Don't send option updates when changing values to the same value

- api/src/main/java/com/lunarclient/apollo/module/title/Title.java
- bukkit-example/src/main/java/com/lunarclient/apollo/example/modules/TitleExample.java
- common/src/main/java/com/lunarclient/apollo/module/title/TitleModuleImpl.java
- docs/developers/modules/title.mdx
**Overview**
This PR adds two properties to the `Title` class:
1. `interpolationScale`
- Allows the title to dynamically expand or shrink based on the provided scale.
- If the scale exceeds the current `Title#scale`, the title expands; otherwise, it shrinks.
2. `interpolationRate`
- Controls the speed of title expansion or shrinkage.
- Defines the rate at which the title adjusts its size every _tick_ (50ms) between the current `scale` and the target `interpolationScale`.
**Example**
In the provided example, the title scale starts small at `0.1` and gradually increases by `0.01` every tick until reaching `1.0` or the title expires.
```java
Title interpolatedTitle = Title.builder()
.type(TitleType.TITLE)
.message(Component.text()
.content("This title expands!")
.color(NamedTextColor.GREEN) …
```
> Feature - Title scale interpolation

- common/src/main/java/com/lunarclient/apollo/option/OptionsImpl.java
Makes it so the client can extend OptionsImpl which broke with #101
> Remove final from OptionsImpl

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/pull_request_template.md
Adds a config file to create this selection menu, after clicking 'New Issue'.
After clicking 'Get Started' on the 'Bug Report' option you're then prompted with a form, which can be viewed below, hopefully a form will help keep everything organized while providing more clarity on certain issues. Using the form will also automatically apply the status label 'Pending' and type label 'Bug'.
Lastly, we have the PR template. It adds text to the description of PRs to ensure everything is in order before opening the PR.
> Add Issue & Pull Request Templates

- .github/workflows/deploy.yml
**Description**
Allows publishing on branches prefixed with `version/`
This will be used for releasing future versions of Apollo. Rather than merging pull requests directly into **master**, we merge to a designated **version** branch first.
> Publish version branches

- bukkit-example/src/main/java/com/lunarclient/apollo/example/modules/HologramExample.java
- docs/developers/modules/hologram.mdx
Fixes a typo for the hologram example location.
**Changes:**
Changes one of the `z` coordinates to an `x` coordinate, since there were two `z` coordinates.
---
---
> Fix - Hologram example typo

- bukkit/src/main/java/com/lunarclient/apollo/ApolloBukkitPlatform.java
- bukkit/src/main/java/com/lunarclient/apollo/command/BukkitApolloCommand.java
- bukkit/src/main/java/com/lunarclient/apollo/command/impl/ApolloCommand.java
- bukkit/src/main/java/com/lunarclient/apollo/command/impl/LunarClientCommand.java
- bukkit/src/platform-loader/resources/plugin.yml
- bungee/src/main/java/com/lunarclient/apollo/ApolloBungeePlatform.java
- bungee/src/main/java/com/lunarclient/apollo/command/BungeeApolloCommand.java
- bungee/src/main/java/com/lunarclient/apollo/command/impl/ApolloCommand.java
- bungee/src/main/java/com/lunarclient/apollo/command/impl/LunarClientCommand.java
- common/src/main/java/com/lunarclient/apollo/command/AbstractApolloCommand.java
- docs/server-owners/commands.mdx
- velocity/src/main/java/com/lunarclient/apollo/ApolloVelocityPlatform.java
- velocity/src/main/java/com/lunarclient/apollo/command/VelocityApolloCommand.java
- velocity/src/main/java/com/lunarclient/apollo/command/impl/ApolloCommand.java
- velocity/src/main/java/com/lunarclient/apollo/command/impl/LunarClientCommand.java
Add `/lunarclient` command to check if a player is _using_ Lunar Client.
**Changes:**
Other than adding the LunarClient command, I made some small improvements to the Apollo command system which included adding a respected implementation for each platform (e.g. `BukkitApolloCommand`) which implements a method for handling a player argument easily.
---
---
> Feature - LunarClient Command

- .github/workflows/deploy.yml
Allows GitHub releases to be created on the branches that start with `version/`.
**Changes**
While releasing version `1.0.9`, we encountered an issue wherein the deployment process failed after merging the `version/1.0.9` branch into `master`. This occurred because the deployment had already successfully run on the `version/` branch, which was marked for release. This code will fix it by allowing the `version/` branch to create the release.
---
> Allow releases on version branches

- api/src/main/java/com/lunarclient/apollo/module/tntcountdown/TntCountdownModule.java
- bukkit/build.gradle.kts
- bukkit/src/main/java/com/lunarclient/apollo/module/tntcountdown/TntCountdownModuleImpl.java
- docs/developers/modules/tntcountdown.mdx
Adds a configuration option to ignore setting the custom TNT countdown ticks on TNT that has a non-default (80 ticks) duration. 
**Changes:**
If the `OVERRIDE_CUSTOM_TICKS` option is false, and the TNT fuse duration is not the default, it will send that duration for that TNTs countdown and not override it with the custom one.
**Related Issue (If applicable):**
https://github.com/LunarClient/Apollo/issues/98
---
---
> Ignore TNT spawned with a custom fuse duration

- .github/workflows/deploy.yml
Currently, the automated GitHub Release process utilizes the latest commit from the `master` branch, which poses an issue for us. The GitHub Actions, including the release steps, are executed on a different branch, causing discrepancies in the release process.
**Changes:**
Utilized the `github.sha` context variable to set the target commit for the release, ensuring it reflects the latest commit on the triggering branch.
---
> Fix - GitHub Release using the wrong commit

- bukkit/src/main/java/com/lunarclient/apollo/module/tntcountdown/TntCountdownModuleImpl.java
Fixes the TNT countdown module.
**Changes:**
Checks the `EntityType#name` string against the legacy and modern name, instead of using the legacy enum.
**Related Issue (If applicable):**
https://github.com/LunarClient/Apollo/issues/148
---
---
> Fix - TNT Countdown Module on 1.20.5+

- docs/developers/modules/transfer.mdx
This PR adds a section to the transfer packet page regarding how DNS-based whitelisting, and the auto-accept system, works.
Link to the page: https://7f6b3843.lunarclient-dev.pages.dev/apollo/developers/modules/transfer
**Changes:**
N/A
**Code Example (If applicable):**
N/A
**Related Issue (If applicable):**
Was discussed in developer Discord.
---
---
> chore: add docs on DNS-based transfer whitelist

- common/src/main/java/com/lunarclient/apollo/option/OptionsImpl.java
This commit corrects the issue by converting the `Color` object to its RGB hex string representation. The problem was that attempting to cast a `java.awt.Color` object to a `String` caused a `ClassCastException` in newer Java versions. The fix ensures that color values can be set using either HEX strings or `Color` objects without causing exceptions.
This pull request resolves the issue where attempting to cast a `java.awt.Color` object to a `String` caused a `ClassCastException` in newer Java versions. The problem arose when handling color values that could be either HEX strings or `Color` objects.
**Changes:**
The code has been updated to properly handle both `String` and `Color` inputs when setting color values. Specifically:
- If the `current` value is a `String`, it …
> fix: ClassCastException for Color conversion in newer Java versions

- api/src/main/java/com/lunarclient/apollo/player/ApolloPlayer.java
- bukkit/build.gradle.kts
- bukkit/src/main/java/com/lunarclient/apollo/ApolloBukkitPlatform.java
- bukkit/src/main/java/com/lunarclient/apollo/wrapper/BukkitApolloPlayer.java
- bungee/build.gradle.kts
- bungee/src/main/java/com/lunarclient/apollo/ApolloBungeePlatform.java
- bungee/src/main/java/com/lunarclient/apollo/wrapper/BungeeApolloPlayer.java
- gradle/libs.versions.toml
- velocity/src/main/java/com/lunarclient/apollo/wrapper/VelocityApolloPlayer.java
Makes the `ApolloPlayer` an `Audience` so it can be used with Adventure better.
**Code Example (If applicable):**
```java
Apollo.getPlayerManager().getPlayer(UUID.randomUUID())
.ifPresent(player -> player.sendMessage(Component.text("Hello World!")));
```
---
---
> Feature - Make `ApolloPlayer` an `Audience`

- docs/downloads.mdx
Our paths in the documentation builder were always a little odd, since we fixed them we also need to update the download page.
**Changes:**
Updates the assets to no longer be prefixed with `/asset`
---
---
> Update Documentation Image Paths

- api/src/main/java/com/lunarclient/apollo/event/player/ApolloPlayerHandshakeEvent.java
- api/src/main/java/com/lunarclient/apollo/module/tebex/TebexEmbeddedCheckoutSupport.java
- api/src/main/java/com/lunarclient/apollo/module/tebex/TebexModule.java
- api/src/main/java/com/lunarclient/apollo/player/ApolloPlayer.java
- bukkit-example/src/main/resources/plugin.yml
- bukkit/src/platform-loader/resources/plugin.yml
- bungee/src/platform-loader/resources/plugin.yml
- common/src/main/java/com/lunarclient/apollo/module/tebex/TebexModuleImpl.java
- deploy.sh
- gradle.properties
- velocity/src/main/java/com/lunarclient/apollo/ApolloVelocityPlatform.java
> Bump to 1.1.6

- bukkit-example/src/main/java/com/lunarclient/apollo/example/api/examples/BorderApiExample.java
- docs/developers/events.mdx
- docs/developers/modules/beam.mdx
- docs/developers/modules/border.mdx
- docs/developers/modules/chat.mdx
- docs/developers/modules/coloredfire.mdx
- docs/developers/modules/cooldown.mdx
- docs/developers/modules/entity.mdx
- docs/developers/modules/glow.mdx
- docs/developers/modules/hologram.mdx
- docs/developers/modules/limb.mdx
- docs/developers/modules/modsetting.mdx
- docs/developers/modules/nametag.mdx
- docs/developers/modules/nickhider.mdx
- docs/developers/modules/notification.mdx
- docs/developers/modules/richpresence.mdx
- docs/developers/modules/serverrule.mdx
- docs/developers/modules/staffmod.mdx
- docs/developers/modules/stopwatch.mdx
- docs/developers/modules/title.mdx
- docs/developers/modules/tntcountdown.mdx
- docs/developers/modules/transfer.mdx
- docs/developers/modules/vignette.mdx
- docs/developers/modules/waypoint.mdx
- docs/developers/options.mdx
- docs/downloads.mdx
- docs/internals/protocol-buffers.mdx
- docs/introduction.mdx
- docs/server-owners/commands.mdx
- docs/server-owners/config.mdx
Preview: https://22b3f8fd.lunarclient-dev.pages.dev/
> Various documentation improvements

- bukkit-example/src/main/java/com/lunarclient/apollo/example/api/examples/ChatApiExample.java
- bukkit-example/src/main/java/com/lunarclient/apollo/example/json/examples/ChatJsonExample.java
- bukkit-example/src/main/java/com/lunarclient/apollo/example/proto/examples/ChatProtoExample.java
- docs/developers/modules/chat.mdx
- docs/developers/modules/team.mdx
- docs/developers/modules/waypoint.mdx
Lightweight Documentation Fixes & Improvements
**Changes:**
- Update Chat Module [example](https://c02ad92f.lunarclient-dev.pages.dev/apollo/developers/modules/chat#displaying-a-live-chat-message) to be a live countdown
- Fix Waypoint Json [example](https://c02ad92f.lunarclient-dev.pages.dev/apollo/developers/modules/waypoint) hyperlink 
---
---
> Lightweight Documentation Fixes & Improvements

- api/src/main/java/com/lunarclient/apollo/module/combat/CombatModule.java
- bukkit-example/src/main/java/com/lunarclient/apollo/example/json/listeners/ApolloPlayerJsonListener.java
- bukkit-example/src/main/java/com/lunarclient/apollo/example/proto/listeners/ApolloPlayerProtoListener.java
- docs/developers/lightweight/json/player-detection.mdx
- docs/developers/lightweight/protobuf/player-detection.mdx
- docs/developers/modules/border.mdx
- docs/developers/modules/combat.mdx
- docs/developers/modules/glow.mdx
- Adjust `CombatModule#DISABLE_MISS_PENALTY` documentation due to added support for versions above 1.8
- Add Fast Renderer callout due to different behavior while Fast Render is enabled
- Fix Lightweight Player Detection examples not matching
---
---
> Docs - Improvements

- docs/developers/modules/combat.mdx
**Changes:**
[Preview](https://450950f9.lunarclient-dev.pages.dev/apollo/developers/modules/combat)
---
---
> Documentation - Add Combat Module lightweight examples

- bukkit-example/src/main/java/com/lunarclient/apollo/example/ApolloExamplePlugin.java
- bukkit-example/src/main/java/com/lunarclient/apollo/example/common/ItemUtil.java
- bukkit-example/src/main/java/com/lunarclient/apollo/example/common/commands/module/GlintCommand.java
- bukkit-example/src/main/java/com/lunarclient/apollo/example/common/commands/module/InventoryCommand.java
- bukkit-example/src/main/java/com/lunarclient/apollo/example/common/commands/module/SaturationCommand.java
- bukkit-example/src/main/java/com/lunarclient/apollo/example/common/modules/impl/GlintExample.java
- bukkit-example/src/main/java/com/lunarclient/apollo/example/common/modules/impl/InventoryExample.java
- bukkit-example/src/main/java/com/lunarclient/apollo/example/common/modules/impl/NMSExample.java
- bukkit-example/src/main/java/com/lunarclient/apollo/example/common/modules/impl/SaturationExample.java
- bukkit-example/src/main/resources/plugin.yml
- docs/developers/modules/_meta.json
- docs/developers/modules/glint.mdx
- docs/developers/modules/inventory.mdx
- docs/developers/modules/saturation.mdx
The `Inventory Module` introduces new NBT tags that enhance item interactions within a player's inventory. This feature enables custom behaviors such as making items unclickable, copying text to the clipboard, opening URLs, and executing commands.
**Changes:**
Introduced new NBT tags to items.
- **Unclickable**: Prevents interaction with items.
- **Copy To Clipboard**: Copies predefined text to a player's clipboard.
- **Open URL**: Opens a specified URL when clicked.
- **Suggest Command**: Suggests a command in the chat input field.
- **Run Command**: Executes a command upon clicking the item.
Added code & command examples for the Glint & Saturation module
**Command Example**
Unclickable Item
```java
/summon item ~ ~1 ~ …
```
> Feature - Inventory Module

- api/src/main/java/com/lunarclient/apollo/module/autotexthotkey/AutoTextHotkeyModule.java
- bukkit-example-api/src/main/java/com/lunarclient/apollo/example/api/ApolloApiExamplePlatform.java
- bukkit-example-api/src/main/java/com/lunarclient/apollo/example/api/module/AutoTextHotkeyApiExample.java
- bukkit-example-api/src/main/resources/plugin.yml
- bukkit-example-common/src/main/java/com/lunarclient/apollo/example/ApolloExamplePlugin.java
- bukkit-example-common/src/main/java/com/lunarclient/apollo/example/command/AutoTextHotkeyCommand.java
- bukkit-example-common/src/main/java/com/lunarclient/apollo/example/module/impl/AutoTextHotkeyExample.java
- bukkit-example-json/src/main/java/com/lunarclient/apollo/example/json/ApolloJsonExamplePlatform.java
- bukkit-example-json/src/main/java/com/lunarclient/apollo/example/json/module/AutoTextHotkeyJsonExample.java
- bukkit-example-json/src/main/resources/plugin.yml
- bukkit-example-proto/src/main/java/com/lunarclient/apollo/example/proto/ApolloProtoExamplePlatform.java
- bukkit-example-proto/src/main/java/com/lunarclient/apollo/example/proto/module/AutoTextHotkeyProtoExample.java
- bukkit-example-proto/src/main/resources/plugin.yml
- bukkit/src/main/java/com/lunarclient/apollo/ApolloBukkitPlatform.java
- bungee/src/main/java/com/lunarclient/apollo/ApolloBungeePlatform.java
- docs/developers/modules/_meta.json
- docs/developers/modules/autotexthotkey.mdx
- velocity/src/main/java/com/lunarclient/apollo/ApolloVelocityPlatform.java
The **Auto Text Hotkey Module** allows servers to provide a list of inputs that are blocked from being used within the **Auto Text Hotkey Mod** 
**Changes:**
Available options
- `BLOCK_TEXT_INPUTS`
- Whether to use blocked text inputs in the `BLOCKED_TEXT_INPUTS` option.
- Values
- Type: `Boolean`
- Default: `false`
- `BLOCKED_TEXT_INPUTS`
- A list of text inputs that are blocked and cannot be used by the user.
- Values
- Type: `List<String>`
- Default: `["/sellall", "/msg", "/pay"]`
- `BLOCK_CHAT_MESSAGE_TEXT_INPUTS`
- Whether to block all chat messages from being used as hotkeys.
- Values
- Type: `Boolean`
- Default: `false`
**Code Example:**
Set blocked text inputs
```java
private final AutoTextHotkeyModule autoTextHotkeyModule = …
```
> Feature - Auto Text Hotkey Module

- bukkit-example-api/src/main/java/com/lunarclient/apollo/example/api/ApolloApiExamplePlatform.java
- bukkit-example-api/src/main/java/com/lunarclient/apollo/example/api/debug/Debug.java
- bukkit-example-api/src/main/java/com/lunarclient/apollo/example/api/debug/DebugManager.java
- bukkit-example-api/src/main/java/com/lunarclient/apollo/example/api/debug/DebugTask.java
- bukkit-example-api/src/main/java/com/lunarclient/apollo/example/api/debug/command/ApolloDebugCommand.java
- bukkit-example-api/src/main/java/com/lunarclient/apollo/example/api/debug/command/BordersCommand.java
- bukkit-example-api/src/main/java/com/lunarclient/apollo/example/api/debug/command/SpamPacketsCommand.java
- bukkit-example-api/src/main/java/com/lunarclient/apollo/example/api/debug/impl/BorderCollisionTest.java
- bukkit-example-api/src/main/java/com/lunarclient/apollo/example/api/debug/impl/SpamPacketDebug.java
- bukkit-example-api/src/main/java/com/lunarclient/apollo/example/api/debug/payload/PayloadListener.java
- bukkit-example-common/src/main/java/com/lunarclient/apollo/example/module/NMSExample.java
Introduce a functional test to verify border collisions for the `Border Module`
**Changes:**
Implemented `BorderCollisionTest`, which fails if the player moves outside the expected bounds:
- Displays a single 1x1 border.
- Applies randomized velocity to push the player against the border walls.
- Clears the border and resets the player's position.
- Displays four 1x1 borders (north, south, east, west) surrounding the player.
- Applies randomized velocity again
- Added a `/apollodebug borders [start|stop]` command to run the test.
**Screenshots and/or Videos:**
https://github.com/user-attachments/assets/4c684f25-a9bd-4d62-b890-752ebfb5865f
---
---
> Test Framework - Add Apollo payload & Border collision tests   

- api/src/main/java/com/lunarclient/apollo/module/glow/GlowModule.java
- common/src/main/java/com/lunarclient/apollo/module/glow/GlowModuleImpl.java
- docs/developers/modules/glow.mdx
Introduce a new **Glow Module** API method that allows overriding the glow effect for a player without explicitly specifying a color. When no color is provided, the glow effect will fall back to the player's scoreboard team color.
**Changes:**
- Added `GlowModule#overrideGlow(Recipients, UUID)` method, supporting scoreboard team color fallback.
- Updated internal implementation to handle `null` color values.
- Updated documentation to reflect fallback behavior.
**Code Example:**
```java
public void overrideGlowEffectExample(UUID glowingPlayer) {
this.glowModule.overrideGlow(Recipients.ofEveryone(), glowingPlayer);
}
```
---
---
> Glow Module - Add Scoreborard Team Color Fallback

- api/src/main/java/com/lunarclient/apollo/event/packetenrichment/chat/ApolloPlayerChatCloseEvent.java
- api/src/main/java/com/lunarclient/apollo/event/packetenrichment/chat/ApolloPlayerChatOpenEvent.java
- api/src/main/java/com/lunarclient/apollo/event/packetenrichment/melee/ApolloPlayerAttackEvent.java
- api/src/main/java/com/lunarclient/apollo/event/packetenrichment/world/ApolloPlayerUseItemEvent.java
- common/src/main/java/com/lunarclient/apollo/module/packetenrichment/PacketEnrichmentImpl.java
- docs/developers/events.mdx
Add the packet sender (`ApolloPlayer`) to all Packet Enrichment Module Events.
**Changes:**
Added `player` field to:
- `ApolloPlayerChatCloseEvent`
- `ApolloPlayerChatOpenEvent`
- `ApolloPlayerAttackEvent`
- `ApolloPlayerUseItemEvent`
**Code Example**
```java
@Listen
private void onApolloPlayerChatClose(ApolloPlayerChatCloseEvent event) {
ApolloPlayer sender = event.getPlayer();
}
```
---
---
> Improvement - Include the packet sender in Packet Enrichment Events

- api/src/main/java/com/lunarclient/apollo/module/title/TitleModule.java
- bukkit-example-api/src/main/java/com/lunarclient/apollo/example/api/module/TitleApiExample.java
- bukkit-example-common/src/main/java/com/lunarclient/apollo/example/command/TitleCommand.java
- bukkit-example-common/src/main/java/com/lunarclient/apollo/example/module/impl/TitleExample.java
- bukkit-example-json/src/main/java/com/lunarclient/apollo/example/json/module/TitleJsonExample.java
- bukkit-example-json/src/main/java/com/lunarclient/apollo/example/json/util/JsonPacketUtil.java
- bukkit-example-proto/src/main/java/com/lunarclient/apollo/example/proto/module/TitleProtoExample.java
- bukkit-example-proto/src/main/java/com/lunarclient/apollo/example/proto/util/ProtobufPacketUtil.java
- docs/developers/lightweight/json/packet-util.mdx
- docs/developers/lightweight/protobuf/packet-util.mdx
- docs/developers/modules/title.mdx
Adds a `CLEAR_TITLE_ON_SERVER_SWITCH` option to the **Title Module** allowing titles to be automatically cleared when a player switches servers.
**Changes:**
Available options
- __`CLEAR_TITLE_ON_SERVER_SWITCH`__
- Determines whether the players displayed title should clear when switching servers.
- Values
- Type: `Boolean`
- Default: `false`
**Code Example**
```java
public void setClearTitleOnServerSwitch(boolean value) {
this.titleModule.getOptions().set(TitleModule.CLEAR_TITLE_ON_SERVER_SWITCH, value);
}
```
```java
public void setClearTitleOnServerSwitch(boolean value) {
Map<String, Value> properties = new HashMap<>();
properties.put("clear-title-on-server-switch", Value.newBuilder().setBoolValue(value).build());
ConfigurableSettings settings = …
```
> Title Module - Add a option to clear the title on server switch

- api/build.gradle.kts
- build-logic/src/main/kotlin/apollo.base-conventions.gradle.kts
- bukkit/src/main/java/com/lunarclient/apollo/ApolloBukkitPlatform.java
- bukkit/src/main/java/com/lunarclient/apollo/listener/ApolloMetadataListener.java
- bukkit/src/main/java/com/lunarclient/apollo/metadata/BukkitMetadata.java
- bukkit/src/main/java/com/lunarclient/apollo/metadata/BukkitMetadataManager.java
- bukkit/src/main/java/com/lunarclient/apollo/util/ByteBufUtil.java
- bungee/src/main/java/com/lunarclient/apollo/ApolloBungeePlatform.java
- bungee/src/main/java/com/lunarclient/apollo/listener/ApolloMetadataListener.java
- bungee/src/main/java/com/lunarclient/apollo/metadata/BungeeMetadata.java
- bungee/src/main/java/com/lunarclient/apollo/metadata/BungeeMetadataManager.java
- bungee/src/main/java/com/lunarclient/apollo/util/ByteBufUtil.java
- common/src/main/java/com/lunarclient/apollo/ApolloManager.java
- common/src/main/java/com/lunarclient/apollo/api/ApolloHttpManager.java
- common/src/main/java/com/lunarclient/apollo/api/request/heartbeat/ServerHeartbeatRequest.java
- common/src/main/java/com/lunarclient/apollo/stats/ApolloStatsManager.java
- common/src/main/java/com/lunarclient/apollo/stats/ApolloStatsThread.java
- common/src/main/java/com/lunarclient/apollo/stats/metadata/ApolloMetadataManager.java
- common/src/main/java/com/lunarclient/apollo/stats/metadata/PlatformMetadata.java
- folia/src/main/java/com/lunarclient/apollo/ApolloFoliaPlatform.java
- folia/src/main/java/com/lunarclient/apollo/listener/ApolloMetadataListener.java
- folia/src/main/java/com/lunarclient/apollo/metadata/FoliaMetadata.java
- folia/src/main/java/com/lunarclient/apollo/metadata/FoliaMetadataManager.java
- gradle/libs.versions.toml
- velocity/build.gradle.kts
- velocity/src/main/java/com/lunarclient/apollo/ApolloVelocityPlatform.java
- velocity/src/main/java/com/lunarclient/apollo/listener/ApolloMetadataListener.java
- velocity/src/main/java/com/lunarclient/apollo/metadata/VelocityMetadata.java
- velocity/src/main/java/com/lunarclient/apollo/metadata/VelocityMetadataManager.java
- velocity/src/main/java/com/lunarclient/apollo/util/ByteBufUtil.java
Add cross-platform user metadata reporting to the `ServerHeartbeatRequest` request.
**Changes:**
- Add `user-metadata` config key under the `mcstats` section
- Update **Velocity-API** version from `3.0.1` to `3.3.0-SNAPSHOT`  
- **Bukkit & Folia**
- Client Brands: A set of unique client brands from players.
- Resource Pack Statuses: A map counting each resource pack status.
- **Bungee**
- Client Brands: A set of unique client brands from connecting players.
- Forge Mods: A map of Forge mod IDs to their versions.
- Server Addresses: A set of unique server addresses (`address:port`) players used to connect.
- **Velocity**
- Client Brands: A set of unique client brands from players.  
- Forge Mods: A map of Forge mod IDs to their versions.  
- Server Addresses: A set of …
> Feature - User Metadata
