LunarClient/Apollo

- bukkit/src/main/java/com/lunarclient/apollo/ApolloBukkitPlatform.java
- bungee/src/main/java/com/lunarclient/apollo/ApolloBungeePlatform.java
- bungee/src/main/java/com/lunarclient/apollo/listener/ApolloPlayerListener.java
- common/src/main/java/com/lunarclient/apollo/network/ApolloNetworkManager.java
- velocity/src/main/java/com/lunarclient/apollo/ApolloVelocityPlatform.java
- velocity/src/main/java/com/lunarclient/apollo/listener/ApolloPlayerListener.java
Fix registering of Apollo players on velocity & bungee
Handle incoming Apollo packets from clients
Add non world / entity based modules
> Fix - Velocity & Bungee Platform

- docs/developers/modules/chat.mdx
Fixed the method for Displaying and Removing Live Messages being incorrect. 
Updated the field name of "liveMessageModule" to "chatModule" to be inline with other module documentation
> Update Chat Module Documentation

- api/src/main/java/com/lunarclient/apollo/player/ApolloPlayer.java
- bukkit-example/src/main/java/com/lunarclient/apollo/example/ApolloExamplePlugin.java
- bukkit-example/src/main/java/com/lunarclient/apollo/example/listeners/PlayerListener.java
- bukkit/src/main/java/com/lunarclient/apollo/wrapper/BukkitApolloPlayer.java
- velocity/src/main/java/com/lunarclient/apollo/wrapper/VelocityApolloPlayer.java
Enable certain features by default in the example plugin.
**Changes:**
The following features will be enabled when a player joins the server
- Team Markers
- Beam
- Border
- Cooldown
- Nametag
- Waypoint
---
---
> Feature - Default features in the example plugin

- bukkit-example/src/main/resources/plugin.yml
- bukkit/src/platform-loader/resources/plugin.yml
- bungee/src/platform-loader/resources/plugin.yml
- deploy.sh
- gradle.properties
- velocity/src/main/java/com/lunarclient/apollo/ApolloVelocityPlatform.java
> Bump Apollo to 1.0.9

- bukkit-example/src/main/java/com/lunarclient/apollo/example/listeners/GeneralListenerExample.java
- docs/developers/events.mdx
Update the event listener example with a working example.
**Changes:**
We were incorrectly accessing the Bukkit's `Player` object from the `ApolloPlayer`.
---
---
> Update event listener example

- api/src/main/java/com/lunarclient/apollo/module/ApolloModule.java
- api/src/main/java/com/lunarclient/apollo/module/packetenrichment/PacketEnrichmentModule.java
- common/src/main/java/com/lunarclient/apollo/module/ApolloModuleManagerImpl.java
- docs/developers/modules/packetenrichment.mdx
Disable Packet Enrichment module by default
---
> Disable Packet Enrichment module by default

- bukkit-example/src/main/resources/plugin.yml
- bukkit/src/platform-loader/resources/plugin.yml
- bungee/src/platform-loader/resources/plugin.yml
- deploy.sh
- gradle.properties
- velocity/src/main/java/com/lunarclient/apollo/ApolloVelocityPlatform.java
> Bump to 1.1.0

- .github/workflows/deploy.yml
- api/src/main/java/com/lunarclient/apollo/module/ApolloModule.java
- api/src/main/java/com/lunarclient/apollo/module/packetenrichment/PacketEnrichmentModule.java
- api/src/main/java/com/lunarclient/apollo/module/tntcountdown/TntCountdownModule.java
- bukkit-example/src/main/java/com/lunarclient/apollo/example/listeners/GeneralListenerExample.java
- bukkit-example/src/main/resources/plugin.yml
- bukkit/build.gradle.kts
- bukkit/src/main/java/com/lunarclient/apollo/module/tntcountdown/TntCountdownModuleImpl.java
- bukkit/src/platform-loader/resources/plugin.yml
- bungee/src/platform-loader/resources/plugin.yml
- common/src/main/java/com/lunarclient/apollo/module/ApolloModuleManagerImpl.java
- deploy.sh
- docs/developers/events.mdx
- docs/developers/modules/packetenrichment.mdx
- docs/developers/modules/tntcountdown.mdx
- docs/developers/utilities/icons.mdx
- gradle.properties
- velocity/src/main/java/com/lunarclient/apollo/ApolloVelocityPlatform.java
- #121 
- #122 
- #123 
- #124 
- #125 
- #126
> Version - 1.1.0

- api/src/main/java/com/lunarclient/apollo/mods/Mods.java
- api/src/main/java/com/lunarclient/apollo/mods/impl/ModGlintColorizer.java
- api/src/main/java/com/lunarclient/apollo/mods/impl/ModHorseStats.java
- api/src/main/java/com/lunarclient/apollo/mods/impl/ModPing.java
- api/src/main/java/com/lunarclient/apollo/mods/impl/ModPotionEffects.java
- api/src/main/java/com/lunarclient/apollo/mods/impl/ModSkyblock.java
- api/src/main/java/com/lunarclient/apollo/mods/impl/ModTab.java
- docs/developers/mods/_meta.json
- docs/developers/mods/glintcolorizer.mdx
- docs/developers/mods/horsestats.mdx
- docs/developers/mods/nametag.mdx
- docs/developers/mods/ping.mdx
- docs/developers/mods/potioneffects.mdx
- docs/developers/mods/skyblock.mdx
- docs/developers/mods/tab.mdx
Auto Generate new Lunar Client Mods & Options
---
---
> Sync LunarClient Mods & Options

- bukkit-example/src/main/resources/plugin.yml
- bukkit/src/platform-loader/resources/plugin.yml
- bungee/src/platform-loader/resources/plugin.yml
- deploy.sh
- gradle.properties
- velocity/src/main/java/com/lunarclient/apollo/ApolloVelocityPlatform.java
> Bump to 1.1.1

- bukkit-example/src/main/java/com/lunarclient/apollo/example/modules/NotificationExample.java
- docs/developers/modules/notification.mdx
Updated the notification example to test newlines.
**Changes:**
Appends newlines to the existing notification example component with some additional example text.
---
---
> Improve - Notification example to test newlines

- bukkit-example/src/main/java/com/lunarclient/apollo/example/commands/CooldownCommand.java
- bukkit-example/src/main/java/com/lunarclient/apollo/example/listeners/PlayerListener.java
- bukkit-example/src/main/java/com/lunarclient/apollo/example/modules/CooldownExample.java
- docs/developers/modules/cooldown.mdx
- docs/developers/utilities/icons.mdx
Adds an example to show SVG icon support for cooldowns and updates the documentation.
---
---
> Feature - Support SVG icons for cooldowns

- bukkit-example/src/main/resources/plugin.yml
- bukkit/src/platform-loader/resources/plugin.yml
- bungee/src/platform-loader/resources/plugin.yml
- deploy.sh
- gradle.properties
- velocity/src/main/java/com/lunarclient/apollo/ApolloVelocityPlatform.java
> Bump to 1.1.2

- docs/developers/modules/richpresence.mdx
- docs/introduction.mdx
Added a callout to the rich presence module & edited the intro.
> Add Callout to Rich Presence Module

- api/src/main/java/com/lunarclient/apollo/module/notification/Notification.java
- bukkit-example/src/main/java/com/lunarclient/apollo/example/commands/NotificationCommand.java
- bukkit-example/src/main/java/com/lunarclient/apollo/example/modules/NotificationExample.java
- common/src/main/java/com/lunarclient/apollo/module/notification/NotificationModuleImpl.java
- docs/developers/modules/notification.mdx
Adds `Icon` support to Notifications with client-side changes that support SVG format.
**Code Example (If applicable):**
```java
public void displayNotificationItemExample(Player viewer) {
Optional<ApolloPlayer> apolloPlayerOpt = Apollo.getPlayerManager().getPlayer(viewer.getUniqueId());
apolloPlayerOpt.ifPresent(apolloPlayer -> {
this.notificationModule.displayNotification(apolloPlayer, Notification.builder()
.titleComponent(Component.text("UHC Announcement", NamedTextColor.GREEN))
.descriptionComponent(Component.text("UHC starts in 5 minutes...", NamedTextColor.RED)
.appendNewline()
.append(Component.text("Get ready!", NamedTextColor.WHITE))
.appendNewline()
.append(Component.text("Good luck!", NamedTextColor.GOLD))
)
.displayTime(Duration.ofSeconds(5)) …
```
> Feature - Notification Icons & NanoSVG support

- docs/developers/modules/beam.mdx
- docs/developers/modules/chat.mdx
- docs/developers/modules/coloredfire.mdx
- docs/developers/modules/cooldown.mdx
- docs/developers/modules/glow.mdx
- docs/developers/modules/limb.mdx
- docs/developers/modules/modsetting.mdx
- docs/developers/modules/nametag.mdx
- docs/developers/modules/notification.mdx
- docs/developers/modules/richpresence.mdx
- docs/developers/modules/saturation.mdx
- docs/developers/modules/staffmod.mdx
- docs/developers/modules/stopwatch.mdx
- docs/developers/modules/team.mdx
- docs/developers/modules/transfer.mdx
- docs/developers/modules/waypoint.mdx
Adds example images to the module overviews.
Preview on the dev page: https://62c5205f.lunarclient-dev.pages.dev/apollo/developers/modules/cooldown
> Add showcase image to module overviews

- bukkit-example/src/main/resources/plugin.yml
- bukkit/src/platform-loader/resources/plugin.yml
- bungee/src/platform-loader/resources/plugin.yml
- deploy.sh
- gradle.properties
- velocity/src/main/java/com/lunarclient/apollo/ApolloVelocityPlatform.java
> Bump to 1.1.3

- bukkit-example/src/main/resources/plugin.yml
- bukkit/src/platform-loader/resources/plugin.yml
- bungee/src/platform-loader/resources/plugin.yml
- deploy.sh
- gradle.properties
- velocity/src/main/java/com/lunarclient/apollo/ApolloVelocityPlatform.java
> Bump to 1.1.4

- api/src/main/java/com/lunarclient/apollo/mods/impl/ModChat.java
- api/src/main/java/com/lunarclient/apollo/mods/impl/ModHypixelMod.java
- bukkit-example/src/main/resources/plugin.yml
- bukkit/src/platform-loader/resources/plugin.yml
- bungee/src/platform-loader/resources/plugin.yml
- common/src/main/java/com/lunarclient/apollo/option/OptionsImpl.java
- common/src/main/java/com/lunarclient/apollo/option/config/CommonSerializers.java
- deploy.sh
- docs/developers/mods/chat.mdx
- docs/developers/mods/hypixelmod.mdx
- gradle.properties
- velocity/src/main/java/com/lunarclient/apollo/ApolloVelocityPlatform.java
- #156
- #157 
- #158
- #159
- #155
> Version - 1.1.4

- bukkit-example/src/main/resources/plugin.yml
- bukkit/src/platform-loader/resources/plugin.yml
- bungee/src/platform-loader/resources/plugin.yml
- deploy.sh
- gradle.properties
- velocity/src/main/java/com/lunarclient/apollo/ApolloVelocityPlatform.java
> Bump to 1.1.5

- api/src/main/java/com/lunarclient/apollo/module/tebex/TebexModule.java
- bukkit-example/src/main/java/com/lunarclient/apollo/example/commands/TebexCommand.java
- bukkit-example/src/main/java/com/lunarclient/apollo/example/modules/TebexExample.java
- common/src/main/java/com/lunarclient/apollo/module/tebex/TebexModuleImpl.java
Add an optional locale field to Tebex module
**Changes:**
**Code Example (If applicable):**
```java
```
**Related Issue (If applicable):**
---
---
> Feature - Add Tebex locale field

- docs/developers/modules/waypoint.mdx
Added chat creation section.
Preview: https://d3afc78a.lunarclient-dev.pages.dev/apollo/developers/modules/waypoint#automatic-waypoint-creation-from-chat
> Documentation - Updated Waypoint Module

- .github/ISSUE_TEMPLATE/bug-report.yml
> Update Issue Template

- api/src/main/java/com/lunarclient/apollo/module/glint/GlintModule.java
- api/src/main/java/com/lunarclient/apollo/module/inventory/InventoryModule.java
- api/src/main/java/com/lunarclient/apollo/module/saturation/SaturationModule.java
- bukkit/src/main/java/com/lunarclient/apollo/ApolloBukkitPlatform.java
Added `GlintModule`, `SaturationModule`, and `InventoryModule` to allow servers to fully disable these features if desired.
`InventoryModule` is disabled by default.
---
---
> Feature - NBT Apollo Modules

- bukkit-example/src/main/resources/plugin.yml
- bukkit/src/platform-loader/resources/plugin.yml
- bungee/src/platform-loader/resources/plugin.yml
- deploy.sh
- gradle.properties
- velocity/src/main/java/com/lunarclient/apollo/ApolloVelocityPlatform.java
> Bump to 1.1.7

- bukkit-example-api/src/main/resources/plugin.yml
- bukkit-example-json/src/main/resources/plugin.yml
- bukkit-example-proto/src/main/resources/plugin.yml
- bukkit/src/platform-loader/resources/plugin.yml
- bungee/src/platform-loader/resources/plugin.yml
- gradle.properties
- scripts/deploy.sh
- velocity/src/main/java/com/lunarclient/apollo/ApolloVelocityPlatform.java
> Bump to 1.1.8
